### ISSUE TITLE
在 从nav用push进入的列表页面中不管是上拉还是下拉刷新后顶面的位置会不正确

### ISSUE THREAD

**Issue by miws** [ydj/DJRefresh#3]
在 从nav用push进入的列表页面中不管是上拉还是下拉刷新后顶面的位置会不正确,我在顶部加的searchBar位置就不正确了，无法进行search操作，不知要如何修正，还请解决这个问题

**Comment by ydj** [comment]
我使用着每月问题，添加了一个demo，你可以参考一下
