### ISSUE TITLE
我的searchBar与你的例子还是有一定的差别

### ISSUE THREAD

**Issue by miws** [ydj/DJRefresh#4]
我是将searBar放在了tableHeadView里，使用refreshcontrol下拉或者上拉后，searchbar位置就会被推到顶部无法显示了。实际上其他的scrollview也存在这个问题，也就是刷新后refreshcontrol计算的位置不正确。
感觉上是没有考虑nav所占的高度。
但我不会Oc，所以我在refreshdelegate中添加了一个fixRefresh以修正这个问题，使用swift来完成
在controller中实现
    func fixRefresh(){
        var f = view.frame
        if let n = self.navigationController?.navigationBar.frame {
            f.origin.y = n.height + n.origin.y
        }
        view.frame = f
    }
在finish中调用
if ([self.delegate respondsToSelector:@selector(fixRefresh)])
    {
        [_delegate fixRefresh];
    }

**Comment by miws** [comment]
如果你oc实现上面的代码应该就更完善了

**Comment by miws** [comment]
怎么现在不支持uiwebview?

**Comment by miws** [comment]
let rc = RefreshControl(scrollView: webView, delegate: self) 报错，编译不通过

**Comment by ydj** [comment]
RefreshControl是支持tableview有tableHeaderview的情况，你可以看一下demo；
另，webview支持下拉刷新，需要传递 webview.scrollView属性，而不是webview

**Comment by miws** [comment]
嗯，这个我发现了，就是关于nav高度的问题 不知能解决否

**Comment by ydj** [comment]
关于Navigation问题，请查考，demo里面tableHeader的情况，demo中都是push到每个子页的，使用正常；Refreshcontrol和Navigation没有关系，只和scrollview相关，请确保你使用tableview的布局正确。

**Comment by miws** [comment]
我在xcode 6.3.2中新建 swift工程使用确定位置不正确
测试工程位置 https://github.com/miws/testRC
麻烦你看看吧

**Comment by ydj** [comment]
在你的tableController类里面，viewDidLoad方法添加        self.navigationController?.navigationBar.translucent=false;

**Comment by miws** [comment]
谢谢，这样真的可行，但navigationbar默认好像不是透明的吧，为什么这里要显示地指定呢

**Comment by ydj** [comment]
这个分好多情况，默认是透明的，加上图片默认就变成不透明的了，你也可以再进行设置，这些都是布局的问题
