### ISSUE TITLE
下拉松手后，会有一个闪动

### ISSUE THREAD

**Issue by ondev** [ydj/DJRefresh#5]
好像是tableview回到顶端，然后再回到松手的offset再向上移动。

**Comment by ydj** [comment]
在_engageRefreshDirection:方法中设置contentOffset

...
_scrollView.contentInset=edge;
        if (direction==DJRefreshDirectionTop) {
            [_scrollView setContentOffset:CGPointMake(0, -edge.top) animated:YES];
        }
...

**Comment by smallgirl** [comment]
与 afn 有冲突，倒入afn 按下home 按键，立马抱错。。。

**Comment by ydj** [comment]
https://github.com/ydj/DJRefresh/issues/6
