### ISSUE TITLE
与UIKit+AFNetworking一起用按下home的时候EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by smallgirl** [ydj/DJRefresh#6]
与UIKit+AFNetworking一起用按下home的时候EXC_BAD_ACCESS

**Comment by ydj** [comment]
贴一些你的代码，看一下你是怎么使用的

**Comment by smallgirl** [comment]
我只是 倒入UIKit+AFNetworking，并没有使用UIKit+AFNetworking的任何代码（后期会用到），倒入后如果 将你的demo 的refesh 的初始化代码注释掉，没有问题，不注释 按下home 键就报错，要不我将代码上传github ，你看看。或者你直接在你的demo 中倒入UIKit+AFNetworking，看看。

**Comment by ydj** [comment]
上传一下你的代码吧

**Comment by smallgirl** [comment]
https://github.com/smallgirl/DJRefresh.git     下面的https://github.com/smallgirl/DJRefresh/blob/master/DJRefreshSample/DJRefreshSample/SampleViewController.m  第44行

**Comment by ydj** [comment]
@smallgirl  这是AFNetworking的issue
 https://github.com/AFNetworking/AFNetworking/issues/2748

解决方法：
Add 
[[NSNotificationCenter defaultCenter] removeObserver:self];
in dealloc method inside category UIActivityIndicatorView+AFNetworking

**Comment by smallgirl** [comment]
Thanks , I had spent one night to find the bug.
